#!/bin/sh

set -eu

# A shell script to create a database of the latest version.
# sqlx macros require an existing database for compile-time
# checking of SQL queries, and this script can be used to
# create one easily. It also generates a readable snapshot of
# the latest database schema.

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
db_file="$repo_dir/test.db"
schema_file="$repo_dir/docs/database-schema.sql"

rm -f "$db_file"

for migration_file in "$repo_dir"/src/migrations/*.sql; do
  sqlite3 "$db_file" <"$migration_file"
done

{
  printf '%s\n' '-- Generated by create_db.sh. Do not edit directly.'
  printf '%s\n\n' '-- Schema snapshot after applying every migration. This is not a migration.'

  sqlite3 "$db_file" <<'SQL'
SELECT sql || ';' || char(10)
FROM sqlite_schema
WHERE sql IS NOT NULL
  AND name NOT LIKE 'sqlite_%'
  AND name NOT IN (
    SELECT name
    FROM pragma_table_list
    WHERE type = 'shadow'
  )
ORDER BY rowid;
SQL
} >"$schema_file"
