-- Generated by create_db.sh. Do not edit directly.
-- Schema snapshot after applying every migration. This is not a migration.

CREATE TABLE `kolib_migrations` (
  `version` INTEGER PRIMARY KEY,
  `title` TEXT NOT NULL,
  `checksum` TEXT NOT NULL, -- SHA-256 hash of the .sql file
  `applied_at` INTEGER DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE platforms (id TEXT PRIMARY KEY NOT NULL);

CREATE TABLE dataset_types (id TEXT PRIMARY KEY NOT NULL);

CREATE TABLE "accounts" (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  platform TEXT NOT NULL,
  user_id TEXT,
  UNIQUE (id, platform),
  FOREIGN KEY (platform) REFERENCES platforms (id) ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TABLE messages (
  id TEXT PRIMARY KEY NOT NULL,
  account_id TEXT NOT NULL,
  platform TEXT NOT NULL,
  conversation_id TEXT NOT NULL,
  record_id TEXT NOT NULL,
  sender TEXT NOT NULL,
  recipient TEXT,
  text TEXT,
  created_at_ms INTEGER,
  FOREIGN KEY (account_id, platform) REFERENCES "accounts" (id, platform) ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE UNIQUE INDEX twitter_message_identity ON messages (account_id, conversation_id, record_id)
WHERE
  platform = 'twitter';

CREATE TABLE message_reactions (
  main_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL,
  -- Stable record identity, supplied by the platform when available or
  -- deterministically derived by the platform parser.
  record_id TEXT,
  sender TEXT,
  reaction TEXT NOT NULL,
  created_at_ms INTEGER,
  PRIMARY KEY (main_id, ordinal),
  FOREIGN KEY (main_id) REFERENCES messages (id) ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE UNIQUE INDEX message_reaction_record_identity ON message_reactions (main_id, record_id)
WHERE
  record_id IS NOT NULL;

CREATE TABLE message_edits (
  main_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL,
  text TEXT NOT NULL,
  created_at_ms INTEGER,
  PRIMARY KEY (main_id, ordinal),
  FOREIGN KEY (main_id) REFERENCES messages (id) ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE message_file_attachments (
  main_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL,
  filename TEXT NOT NULL,
  created_at_ms INTEGER,
  PRIMARY KEY (main_id, ordinal),
  FOREIGN KEY (main_id) REFERENCES messages (id) ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE message_link_attachments (
  main_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL,
  url TEXT NOT NULL,
  created_at_ms INTEGER,
  PRIMARY KEY (main_id, ordinal),
  FOREIGN KEY (main_id) REFERENCES messages (id) ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "account_datasets" (
  account_id TEXT NOT NULL,
  dataset_type TEXT NOT NULL,
  PRIMARY KEY (account_id, dataset_type),
  FOREIGN KEY (account_id) REFERENCES "accounts" (id) ON UPDATE NO ACTION ON DELETE CASCADE,
  FOREIGN KEY (dataset_type) REFERENCES dataset_types (id) ON UPDATE NO ACTION ON DELETE RESTRICT
);

CREATE TRIGGER accounts_validate_name_on_insert BEFORE INSERT ON accounts WHEN length(trim(NEW.name)) NOT BETWEEN 1 AND 100  BEGIN
SELECT
  RAISE (
    ABORT,
    'account name must be between 1 and 100 characters'
  );

END;

CREATE TRIGGER accounts_validate_name_on_update BEFORE
UPDATE OF name ON accounts WHEN length(trim(NEW.name)) NOT BETWEEN 1 AND 100  BEGIN
SELECT
  RAISE (
    ABORT,
    'account name must be between 1 and 100 characters'
  );

END;

CREATE TRIGGER messages_create_dataset AFTER INSERT ON messages BEGIN
INSERT OR IGNORE INTO
  account_datasets (account_id, dataset_type)
VALUES
  (NEW.account_id, 'messages');

END;

CREATE VIRTUAL TABLE messages_fts USING fts5 (
  message_id UNINDEXED,
  text,
  tokenize = 'unicode61'
);

CREATE TRIGGER messages_fts_after_insert AFTER INSERT ON messages BEGIN
INSERT INTO
  messages_fts (message_id, text)
VALUES
  (NEW.id, NEW.text);

END;

CREATE TRIGGER messages_fts_after_delete AFTER DELETE ON messages BEGIN
DELETE FROM messages_fts
WHERE
  message_id = OLD.id;

END;

CREATE TRIGGER messages_fts_after_text_update AFTER
UPDATE OF text ON messages BEGIN
UPDATE messages_fts
SET
  text = NEW.text
WHERE
  message_id = OLD.id;

END;

